/*
 * Generated by XDoclet - Do not edit!
 */
package CurrencyDemo.service;

/**
 * Session layer for Common_COP_S.
 * @wtp generated
 */
public class Common_COP_SSession
   extends CurrencyDemo.service.Common_COP_SBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

      super.ejbActivate();
   }

   public void ejbPassivate() 
   {
      super.ejbPassivate();
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
      super.ejbRemove();
   }

}
