/*
 * Generated by XDoclet - Do not edit!
 */
package CurrencyDemo.service;

/**
 * Local home interface for Common_COP_S.
 * @wtp generated
 */
public interface Common_COP_SLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Common_COP_SLocal";
   public static final String JNDI_NAME="CurrencyDemo/service/Common_COP_SLocal";

   public CurrencyDemo.service.Common_COP_SLocal create()
      throws javax.ejb.CreateException;

}
