/*
 * Generated by XDoclet - Do not edit!
 */
package CurrencyDemo.service;

/**
 * Local interface for Common_COP_S.
 * @wtp generated
 */
public interface Common_COP_SLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Validate the bean's internal mechanics.
    * @param input An arbitrary string which will be embedded in the return string
    * @return A string containing the name of the bean, the name of the current app server (repository name) and the input string.
    */
   public java.lang.String ping( java.lang.String uid,java.lang.String input ) ;

   /**
    * User-defined operation setRemoteUpdateCUR Dummy only for test
    */
   public java.lang.Boolean setRemoteUpdateCUR( java.lang.String uid,java.lang.String sCurrencyCode,java.lang.String sRemoteParm ) throws com.versata.tl.vls.service.ServiceException;

   /**
    * Pre-defined operation createNewDelegate Creates a new instance of the delegate class
    */
   public void createNewDelegate( java.lang.String uid ) throws com.versata.tl.vls.service.ServiceException;

}
